package org.paulsens.trip.chat;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.LinkedHashMap;
import java.util.Map;
import lombok.extern.slf4j.Slf4j;
import org.paulsens.trip.action.ConfigCommands;
import org.paulsens.trip.config.KnownSettings;
import org.paulsens.trip.action.MailCommands;
import org.paulsens.trip.audit.AuditActor;
import org.paulsens.trip.cache.CacheClient;
import org.paulsens.trip.cache.CacheKeys;
import org.paulsens.trip.dynamo.DAO;
import org.paulsens.trip.model.Person;
import org.paulsens.trip.cache.Cached;
import org.paulsens.trip.site.SiteUrls;

/**
 * Sends chat notifications by email.
 *
 * <p>Only {@code MENTION} and {@code ADMIN_ANNOUNCEMENT} arrive immediately. Ordinary messages never do — that is
 * not a tuning choice but the difference between a feature people keep and one they mute in week one: a chatty
 * evening on a 200-person trip would otherwise be thousands of sends and an SES reputation problem.
 */
@Slf4j
public final class EmailChatNotifier implements ChatNotifier {


    private final MailCommands mail;
    private final CacheClient cacheClient;
    private final ConfigCommands config;

    public EmailChatNotifier() {
        this(new MailCommands(), DAO.getInstance().getCacheClient(), new ConfigCommands());
    }

    public EmailChatNotifier(
            final MailCommands mail, final CacheClient cacheClient, final ConfigCommands config) {
        this.mail = mail;
        this.cacheClient = cacheClient;
        this.config = config;
    }

    @Override
    public Channel channel() {
        return Channel.EMAIL;
    }

    /**
     * Off by default.
     *
     * <p>Deliberate: this ships dark so the code can deploy and be exercised before any pilgrim receives mail from
     * it, and so a runaway can be stopped from the config table without a deploy.
     */
    @Override
    public boolean isEnabled() {
        return config.getBoolean(KnownSettings.CHAT_MAIL_ENABLED);
    }

    @Override
    public void notify(final ChatNotification notification) {
        if (notification == null || notification.getReason() == ChatNotification.Reason.ALL_MESSAGES) {
            // ALL_MESSAGES is accepted by the model but never mailed immediately; it belongs to the digest.
            return;
        }
        for (final Person.Id recipient : notification.getRecipients()) {
            sendOne(notification, recipient);
        }
    }

    private void sendOne(final ChatNotification notification, final Person.Id recipient) {
        try {
            deliver(notification, recipient);
        } catch (final RuntimeException ex) {
            // Never propagate: the message this is about has already been acknowledged to its sender.
            log.warn("Unable to email chat notification to {}", recipient, ex);
        }
    }

    private void deliver(final ChatNotification notification, final Person.Id recipient) {
        final String dedupe = ChatNotification.dedupeKeyFor(
                notification.getMessageId(), recipient, channel().name());
        // Claim first. tryAcquireLock returns false when the marker exists, so the first caller wins and a retry or
        // a restart mid-fan-out cannot mail the same person twice.
        if (!claim(dedupe)) {
            return;
        }
        final Person person = DAO.getInstance().getPerson(recipient, Cached.NO).orElse(null);
        final String to = person == null ? null : mail.formatEmail(person);
        if (to == null) {
            log.debug("Skipping chat notification for {}: no usable email address", recipient);
            return;
        }
        final String body = MailTemplates.render(templateFor(notification), mentionValues(notification));
        if (body == null) {
            // Template missing or unrenderable. Sending a half-built mail is worse than sending none.
            return;
        }
        // System: the notification is generated by the application in response to a message, and is delivered
        // asynchronously, so the author is not the one asking for this particular send.
        mail.send(from(), to, null, replyTo(notification), subjectFor(notification), body,
                AuditActor.system());
    }

    private Map<String, Object> mentionValues(final ChatNotification notification) {
        final Map<String, Object> values = new LinkedHashMap<>();
        values.put("authorName", notification.getAuthorName() == null ? "Someone" : notification.getAuthorName());
        values.put("tripTitle", notification.getTripTitle() == null ? "trip" : notification.getTripTitle());
        values.put("chatUrl", urlFor(notification));
        values.put("snippetBlock", snippetBlock(notification));
        return values;
    }

    /** Whether this notification is about a photo comment rather than the trip chat, read off the channel id. */
    private static boolean isPhotoNotification(final ChatNotification notification) {
        return notification.getChannelId() != null && notification.getChannelId().photoKeyOrNull() != null;
    }

    private static String templateFor(final ChatNotification notification) {
        if (notification.getReason() == ChatNotification.Reason.REPLY) {
            return "chat-reply";
        }
        if (notification.getReason() == ChatNotification.Reason.PHOTO_COMMENT) {
            return "photo-comment";
        }
        return isPhotoNotification(notification) ? "photo-mention" : "chat-mention";
    }

    /**
     * Where the mail's link lands: the chat page, or — for a photo comment — the trip album deep-linked to the
     * photo (`?photo=` auto-opens the viewer there).
     */
    private String urlFor(final ChatNotification notification) {
        final String photoKey = notification.getChannelId() == null
                ? null : notification.getChannelId().photoKeyOrNull();
        if (photoKey == null) {
            return chatUrl(notification.getTripId());
        }
        final String tripId = notification.getTripId() == null ? "" : notification.getTripId();
        return baseUrlFor(tripId) + "/trip/tripMedia.jsf?trip=" + tripId
                + "&photo=" + URLEncoder.encode(photoKey, StandardCharsets.UTF_8);
    }

    /**
     * The quoted body, or nothing at all.
     *
     * <p>A short-retention channel sends a content-free notification: an inbox keeps a message for years, so putting
     * the body in an email from a channel configured to forget it in an hour makes the content outlive the retention
     * policy in a place no administrator can reach. {@link ChatNotification#hasSnippet()} carries that decision from
     * the builder, which is the only place that knows the channel's settings.
     */
    private MailTemplates.Raw snippetBlock(final ChatNotification notification) {
        if (!notification.hasSnippet()) {
            return new MailTemplates.Raw("");
        }
        return new MailTemplates.Raw("<blockquote style=\"border-left:3px solid #6c8;padding-left:0.75rem;"
                + "color:#444;margin:1rem 0;\">" + MailTemplates.escape(notification.getSnippet())
                + "</blockquote>");
    }

    private String subjectFor(final ChatNotification notification) {
        final String trip = notification.getTripTitle() == null ? "your trip" : notification.getTripTitle();
        if (notification.getReason() == ChatNotification.Reason.ADMIN_ANNOUNCEMENT) {
            return "Announcement in the " + trip + " chat";
        }
        final String author = notification.getAuthorName() == null ? "Someone" : notification.getAuthorName();
        if (notification.getReason() == ChatNotification.Reason.REPLY) {
            return author + " replied to you in the " + trip + " chat";
        }
        if (notification.getReason() == ChatNotification.Reason.PHOTO_COMMENT) {
            return author + " commented on your photo from the " + trip + " trip";
        }
        if (isPhotoNotification(notification)) {
            return author + " mentioned you on a photo from the " + trip + " trip";
        }
        return author + " mentioned you in the " + trip + " chat";
    }

    private boolean claim(final String dedupeKey) {
        return cacheClient.tryAcquireLock(
                CacheKeys.chatNotifySentKey(dedupeKey), CacheKeys.CHAT_NOTIFY_SENT_TTL);
    }

    String chatUrl(final String tripId) {
        return baseUrlFor(tripId) + "/trip/chat.jsf?trip=" + (tripId == null ? "" : tripId);
    }

    /**
     * The site the link belongs on: the trip's organization's own site when it has one, else the chat
     * base-URL setting. Derived from the TRIP -- this runs off-request under the system context, where no
     * host is bound, and the recipient must land on the site their trip lives on.
     */
    private String baseUrlFor(final String tripId) {
        final org.paulsens.trip.model.Trip trip = (tripId == null || tripId.isBlank()) ? null
                : DAO.getInstance().getTrip(tripId, Cached.YES).orElse(null);
        return SiteUrls.baseUrlForTrip(trip, KnownSettings.CHAT_MAIL_BASE_URL, config);
    }

    private String from() {
        return new org.paulsens.trip.action.MailAddressCommands(config)
                .from(KnownSettings.CHAT_MAIL_FROM);
    }

    /**
     * Reply-To resolves per notification: in {@code org} mode it is the owning organization's contact
     * email, so the trip is looked up from the notification (null-safe -- photo/support channels and a
     * deleted trip fall back to the site email).
     */
    private String replyTo(final ChatNotification notification) {
        final String tripId = notification.getTripId();
        final org.paulsens.trip.model.Trip trip = (tripId == null || tripId.isBlank()) ? null
                : DAO.getInstance().getTrip(tripId, Cached.YES).orElse(null);
        return new org.paulsens.trip.action.MailAddressCommands(config)
                .replyTo(KnownSettings.CHAT_MAIL_REPLY_TO, trip);
    }
}
